### ISSUE TITLE
CA - Duplicate Results Being Sent From ReportStream

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#17232]
## Problem statement

User is receiving an influx of duplicate results lately via ReportStream into CalREDIE.

## What you need to know

Being sent under the CLIA of CDPH000085.

The duplicates started on 1/27/25.

<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0d1Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32a2fdc7e077d81b5a0114892a577eae579236a4/image.png" alt="image.png" />

<img width="1147" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0t1Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc49220f01c467f64e99e405c06f4da35ff5a137/image.png" alt="image.png" />

<img width="463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN091Q0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0274173850b55582471655a36802f8de75c4af81/image.png" alt="image.png" />

## To do

Implement fix to avoid duplicates being sent.

**Comment by MikaelahD13** [comment]
Hey @victor-chaparro please take a look into this discrepancy?

**Comment by chris-kuryak** [comment]
@Jcavallo7 
We have reviewed some of these duplicates and have identified that we think most of them are sender input errors from SimpleReport senders. I am setting up a time to review this with the SimpleReport team and will include you and @TaneaY on the invite.

As of now, we do not have any clear answer to provide CA. But if you'd like to provide a status update to them, I think you can indicate something along the lines of "ReportStream is actively investigating the issue to determine the root cause. We will be working with our senders next week and can provide an update."

**Comment by chris-kuryak** [comment]
Met today between SR, RS, and Support team. Next steps outline:

1. Investigate why some messages were marked as duplicates -- RS will provide Support team with accession numbers and verbiage to respond to Manifest/CA. Support team will comm back to user.
2. Investigate if/why some senders are sending the same "Test_Performed_Code" for multi-plex test results on different conditions -- we think this is triggering duplicates on the CA side, and SR is going to investigate (with the example Victor provided in Slack) if this is a SR Sender issue.

**Comment by chris-kuryak** [comment]
@Jcavallo7 
Here is some suggested content to respond to CA/Manifest with:

To help us troubleshoot the reasoning for all of these being marked as duplicates, can you provide the reason why the results for the following two accession numbers were marked as duplicates? And if it is because they were received a previous date/time, can you provide what date/time they were received and from what source? (Assuming it was not ReportStream.)

- 1261669
- PRO6850201
- 973055

**Comment by chris-kuryak** [comment]
@Jcavallo7 a quick update:

Glenn Grieves had a meeting with CA today and relayed the latest information:
- RS has changed the max batch size to 400 items and reduced the send cadence to once per 10 min

This seems to have fixed the issue as we have not seen any more spikes in duplicates.

Per Glenn, Ellaison at CA will be checking to see if they are continuing to see the issues.
RS will continue to monitor for a bit longer to ensure the issue has been resolved.

**Comment by chris-kuryak** [comment]
Still awaiting response from Manifest. Victor sent email on Tues Mar 18.

**Comment by chris-kuryak** [comment]
Linked with #15588

**Comment by davidcalabrese0324** [comment]
Continuing to troubleshoot with Manifest.

**Comment by davidcalabrese0324** [comment]
Got script for Manifest. @victor-chaparro  running into some issues still, but working through it.

**Comment by davidcalabrese0324** [comment]
@victor-chaparro  set up a meeting to sync and get on the same page with Manifest. Every message we send to CA test environment it fails, but works on our side.
