### ISSUE TITLE
SafeHealth Data Quality Improvement

### ISSUE THREAD

**Issue by brick-green** [CDCgov/prime-reportstream#6489]
## Problem statement

Safe Health is sending incomplete data resulting in issues for STLTs. 

## What you need to know

![image.png](https://images.zenhubusercontent.com/60d23d7dcaf07751be9205b6/8f143244-fd83-43c1-93d2-8b48960fa17b)

**Comment by brick-green** [comment]
Update from SafeHealth

```1. Requested changes for the current CSV file transmission are almost done (undergoing Quality)  on our side and we are planning to release it to Prod by the end of this week.```

**Comment by brick-green** [comment]
SafeHealth reported that the fix would go into production on 9/1. 

@sliu1000 Can you let both receivers know(ticket's attached to this epic) the timeline?

**Comment by sliu1000** [comment]
@brick-green Hi Brick, which state receivers should I alert on this?

**Comment by sliu1000** [comment]
Sent Senders update, please see below the communication to TN - CEDS.Informatics@tn.gov and LA - tania.bechtel@la.gov:

Greetings,

We have been working with the original sender and they advised that they will release their updates into production today.

Thank you for your patience.

Best regards,

Sharon
The ReportStream Support Team

Contact us at reportstream@cdc.gov
Support hours:  8:00 am through 9:00 pm Eastern time
Monday-Friday, excluding US public holidays

**Comment by brick-green** [comment]
SafeHealth is going to send a sample corrected message to staging tomorrow 9/9. If that looks good they will send the full backlog shortly after.

**Comment by brick-green** [comment]
Requested an update from SafeHealth

**Comment by sliu1000** [comment]
Update from SafeHealth:

Dear Brick,

We ran into an issue with one of our providers on Friday, which was resolved over the weekend.
Would you please ask your team to chce following messages that have been sent today to your Stage environment as re-plays:

 "id" : "`8a1928ad-598d-4f21-ac74-7ecb19f416f5`",
        "submissionId" : 3196949,
  2.  "id" : "`eff45593-bdbe-4c4f-a4c7-259d6a85f0a0`",
        "submissionId" : 3196948,

Thank you,

Dmitriy Lurie

**Comment by shy2cdc** [comment]
The below is from Santosh

Hi Brick,

Here is the complete request details that are submitted and also the acknowledgement / response that we received from CDC.
Please review and let us know if anything else is needed for troubleshooting.

Request:
-------------
{
"TestOrdered": "97097-0",
"TestName": "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay",
"TestCodingSystem": "LOINC",
"TestResult": "260373001",
"TestResultText": "DETECTED",
"TestPerformed": "97097-0",
"TestResultCodingSystem": "SCT",
"TestResultDate": "20220905",
"TestReportDate": "20220905",
"TestOrderedDate": "20220905",
"SpecimenCollectedDate": "20220905",
"DeviceIdentifier": "Flowflex COVID-19 Antigen Home Test_ACON Laboratories, Inc",
"DeviceName": "Flowflex COVID-19 Antigen Home Test",
"SpecimenId": "63162fa35d35f5fabac48a47",
"SerialNumber": "63162fa35d35f5fabac48a47",
"PatientAge": "42",
"PatientAgeUnits": "yr",
"CorrectedTestId": "",
"PatientDob": "19800111",
"PatientRace": "UNK",
"PatientRaceText": "Unknown",
"PatientEthnicity": "2186-5",
"PatientEthnicityText": "Non Hispanic or Latino",
"PatientSex": "M",
"PatientZip": "40505",
"PatientCounty": null,
"OrderingProviderNpi": "1043311277",
"OrderingProviderLname": "Pearlman",
"OrderingProviderFname": "Justin",
"OrderingProviderZip": "03756",
"PerformingFacility": "05D2195670",
"PerformingFacilityName": "SAFE PMC",
"PerformingFacilityStreet": "6161 E Mayo Blvd",
"PerformingFacilityStreet2": "Ste 209",
"PerformingFacilityCity": "Phoenix",
"PerformingFacilityState": "AZ",
"PerformingFacilityZip": "Ste 209",
"PerformingFacilityPhone": "",
"PerformingFacilityCounty": "",
"OrderingFacilityName": "SAFE PMC",
"OrderingFacilityStreet": "6161 E Mayo Blvd",
"OrderingFacilityStreet2": "Ste 209",
"OrderingFacilityCity": "Phoenix",
"OrderingFacilityState": "AZ",
"OrderingFacilityZip": "Ste 209",
"OrderingFacilityPhone": "",
"OrderingFacilityCounty": "",
"OrderingFacilityEmail": "",
"SpecimenSource": "697989009",
"PatientNameLast": "Silas",
"PatientNameFirst": "Caleb",
"PatientNameMiddle": "",
"PatientUniqueId": "TPCbhskNuqG2X2",
"PatientHomeAddress": "1 West St",
"PatientHomeAddress2": null,
"PatientCity": "Lexington",
"PatientState": "KY",
"PatientPhone": "8599890909",
"PatientPhoneArea": null,
"OrderingProviderAddress": "ONE MEDICAL CENTER DRIVE",
"OrderingProviderAddress2": "DARTMOUTH HITCHCOCK MEDICAL CENTER",
"OrderingProviderCity": "LEBANON",
"OrderingProviderState": "NH",
"OrderingProviderPhone": "(603) 650-5000",
"OrderingProviderPhoneArea": null,
"FirstTest": "UNK",
"PreviousTestType": null,
"PreviousTestDate": null,
"PreviousTestResult": null,
"HealthcareEmployee": "UNK",
"HealthcareEmployeeType": null,
"Symptomatic": "UNK",
"SymptomsList": null,
"Hospitalized": "UNK",
"HospitalizedCode": null,
"SymptomsIcu": "UNK",
"CongregateResident": "UNK",
"CongregateResidentType": null,
"Pregnant": "261665006",
"PregnantText": "Unknown",
"PatientEmail": "caleb.silas@safehealth.me",
"ReportingFacility": "SAFE PMC"
}




Resposne:
-------------
{
  "id" : "`eff45593-bdbe-4c4f-a4c7-259d6a85f0a0`",
  "submissionId" : 3196948,
  "overallStatus" : "Waiting to Deliver",
  "timestamp" : "2022-09-12T17:50:39.378Z",
  "plannedCompletionAt" : "2022-09-12T18:00:00.000Z",
  "actualCompletionAt" : null,
  "sender" : "safehealth.default",
  "reportItemCount" : 1,
  "errorCount" : 0,
  "warningCount" : 1,
  "httpStatus" : 201,
  "destinations" : [ {
    "organization" : "Arizona PHD",
    "organization_id" : "az-phd",
    "service" : "elr-prod",
    "itemCount" : 1,
    "itemCountBeforeQualityFiltering" : 1,
    "sending_at" : "2022-09-12T17:51:00.000Z",
    "filteredReportRows" : [ ],
    "filteredReportItems" : [ ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  }, {
    "organization" : "HHSProtect",
    "organization_id" : "hhsprotect",
    "service" : "elr",
    "itemCount" : 1,
    "itemCountBeforeQualityFiltering" : 1,
    "sending_at" : "2022-09-12T18:00:00.000Z",
    "filteredReportRows" : [ ],
    "filteredReportItems" : [ ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  }, {
    "organization" : "Kentucky Public Health Department",
    "organization_id" : "ky-phd",
    "service" : "elr",
    "itemCount" : 1,
    "itemCountBeforeQualityFiltering" : 1,
    "sending_at" : "2022-09-12T17:51:00.000Z",
    "filteredReportRows" : [ ],
    "filteredReportItems" : [ ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  } ],
  "actionName" : "receive",
  "externalName" : null,
  "reportId" : "eff45593-bdbe-4c4f-a4c7-259d6a85f0a0",
  "topic" : "covid-19",
  "errors" : [ ],
  "warnings" : [ {
    "scope" : "report",
    "message" : "Unexpected column header found, 'reportingFacility' will be ignored"
  } ],
  "destinationCount" : 3
}



Request 2:
-------------
{
"TestOrdered": "97097-0",
"TestName": "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay",
"TestCodingSystem": "LOINC",
"TestResult": null,
"TestResultText": "INVALID",
"TestPerformed": "97097-0",
"TestResultCodingSystem": "SCT",
"TestResultDate": "20220905",
"TestReportDate": "20220905",
"TestOrderedDate": "20220905",
"SpecimenCollectedDate": "20220905",
"DeviceIdentifier": "Flowflex COVID-19 Antigen Home Test_ACON Laboratories, Inc",
"DeviceName": "Flowflex COVID-19 Antigen Home Test",
"SpecimenId": "VpUXg3RGLbuEon",
"SerialNumber": "VpUXg3RGLbuEon",
"PatientAge": "42",
"PatientAgeUnits": "yr",
"CorrectedTestId": "",
"PatientDob": "19800111",
"PatientRace": "UNK",
"PatientRaceText": "Unknown",
"PatientEthnicity": "2186-5",
"PatientEthnicityText": "Non Hispanic or Latino",
"PatientSex": "M",
"PatientZip": "40505",
"PatientCounty": null,
"OrderingProviderNpi": "1043311277",
"OrderingProviderLname": "Pearlman",
"OrderingProviderFname": "Justin",
"OrderingProviderZip": "03756",
"PerformingFacility": "05D2195670",
"PerformingFacilityName": "SAFE PMC",
"PerformingFacilityStreet": "6161 E Mayo Blvd",
"PerformingFacilityStreet2": "Ste 209",
"PerformingFacilityCity": "Phoenix",
"PerformingFacilityState": "AZ",
"PerformingFacilityZip": "Ste 209",
"PerformingFacilityPhone": "",
"PerformingFacilityCounty": "",
"OrderingFacilityName": "SAFE PMC",
"OrderingFacilityStreet": "6161 E Mayo Blvd",
"OrderingFacilityStreet2": "Ste 209",
"OrderingFacilityCity": "Phoenix",
"OrderingFacilityState": "AZ",
"OrderingFacilityZip": "Ste 209",
"OrderingFacilityPhone": "",
"OrderingFacilityCounty": "",
"OrderingFacilityEmail": "",
"SpecimenSource": "697989009",
"PatientNameLast": "Silas",
"PatientNameFirst": "Caleb",
"PatientNameMiddle": "",
"PatientUniqueId": "TPCbhskNuqG2X2",
"PatientHomeAddress": "1 West St",
"PatientHomeAddress2": null,
"PatientCity": "Lexington",
"PatientState": "KY",
"PatientPhone": "8599890909",
"PatientPhoneArea": null,
"OrderingProviderAddress": "ONE MEDICAL CENTER DRIVE",
"OrderingProviderAddress2": "DARTMOUTH HITCHCOCK MEDICAL CENTER",
"OrderingProviderCity": "LEBANON",
"OrderingProviderState": "NH",
"OrderingProviderPhone": "(603) 650-5000",
"OrderingProviderPhoneArea": null,
"FirstTest": "UNK",
"PreviousTestType": null,
"PreviousTestDate": null,
"PreviousTestResult": null,
"HealthcareEmployee": "UNK",
"HealthcareEmployeeType": null,
"Symptomatic": "UNK",
"SymptomsList": null,
"Hospitalized": "UNK",
"HospitalizedCode": null,
"SymptomsIcu": "UNK",
"CongregateResident": "UNK",
"CongregateResidentType": null,
"Pregnant": "261665006",
"PregnantText": "Unknown",
"PatientEmail": "caleb.silas@safehealth.me",
"ReportingFacility": "SAFE PMC"
}


Response:
----------------
{
  "id" : "`8a1928ad-598d-4f21-ac74-7ecb19f416f5`",
  "submissionId" : 3196949,
  "overallStatus" : "Waiting to Deliver",
  "timestamp" : "2022-09-12T17:50:55.316Z",
  "plannedCompletionAt" : "2022-09-12T18:00:00.000Z",
  "actualCompletionAt" : null,
  "sender" : "safehealth.default",
  "reportItemCount" : 1,
  "errorCount" : 0,
  "warningCount" : 1,
  "httpStatus" : 201,
  "destinations" : [ {
    "organization" : "Arizona PHD",
    "organization_id" : "az-phd",
    "service" : "elr-prod",
    "itemCount" : 0,
    "itemCountBeforeQualityFiltering" : 1,
    "filteredReportRows" : [ "For az-phd.elr-prod, filter hasValidDataFor[test_result] filtered out item VpUXg3RGLbuEon" ],
    "filteredReportItems" : [ {
      "filterType" : "QUALITY_FILTER",
      "filterName" : "hasValidDataFor",
      "filteredTrackingElement" : "VpUXg3RGLbuEon",
      "filterArgs" : [ "test_result" ],
      "message" : "For az-phd.elr-prod, filter hasValidDataFor[test_result] filtered out item VpUXg3RGLbuEon"
    } ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  }, {
    "organization" : "Kentucky Public Health Department",
    "organization_id" : "ky-phd",
    "service" : "elr",
    "itemCount" : 0,
    "itemCountBeforeQualityFiltering" : 1,
    "filteredReportRows" : [ "For ky-phd.elr, filter hasValidDataFor[test_result] filtered out item VpUXg3RGLbuEon" ],
    "filteredReportItems" : [ {
      "filterType" : "QUALITY_FILTER",
      "filterName" : "hasValidDataFor",
      "filteredTrackingElement" : "VpUXg3RGLbuEon",
      "filterArgs" : [ "test_result" ],
      "message" : "For ky-phd.elr, filter hasValidDataFor[test_result] filtered out item VpUXg3RGLbuEon"
    } ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  }, {
    "organization" : "HHSProtect",
    "organization_id" : "hhsprotect",
    "service" : "elr",
    "itemCount" : 1,
    "itemCountBeforeQualityFiltering" : 1,
    "sending_at" : "2022-09-12T18:00:00.000Z",
    "filteredReportRows" : [ ],
    "filteredReportItems" : [ ],
    "sentReports" : [ ],
    "downloadedReports" : [ ]
  } ],
  "actionName" : "receive",
  "externalName" : null,
  "reportId" : "8a1928ad-598d-4f21-ac74-7ecb19f416f5",
  "topic" : "covid-19",
  "errors" : [ ],
  "warnings" : [ {
    "scope" : "report",
    "message" : "Unexpected column header found, 'reportingFacility' will be ignored"
  } ],
  "destinationCount" : 1
}

Thanks
Santosh

**Comment by brick-green** [comment]
responded to their email. There are a few issues with the messages above. OrderingFacilityZip and PerformingFacilityZip are incorrect. TestResult is null for result 2 and correctedID is blank when it should equal the value in SpecimenID.

**Comment by brick-green** [comment]
Future comments should be made on ticket #[6590](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6590)

**Comment by brick-green** [comment]
SafeHealth sent messages to staging for the backlog. I checked them and many still have the same problem of test identifier information misaligning with the LIVD table. Sent my feedback to them.

**Comment by brick-green** [comment]
SafeHealth provided the backlog. @sliu1000 Can you let the states know? Looks like there were 4 states that we have tickets for. All are attached to this epic 

cc @BerniXiongA6

**Comment by sliu1000** [comment]
Sent email to WA, CA, LA and TN the below:

Greetings,

Please be advised that the Sender Safehealth has sent their backlog.

Best regards,

Sharon
